---
- name: Ensure squid installed
  apt:
    name: squid
    cache_valid_time: 3600
    install_recommends: false

- name: Ensure avahi-daemon installed
  apt:
    name: avahi-daemon
    cache_valid_time: 3600
    install_recommends: false
  when: squid_deb_proxy_avahi | bool

- name: Configure service
  template:
    src: "{{ squid_deb_proxy | ternary('squid-deb-proxy.conf.j2','squid.conf.j2') }}"
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/squid -f %s -k parse
  notify: Restart Squid

- name: Configure mDNS service
  template:
    src: squid-deb-proxy.avahi.j2
    dest: /etc/avahi/services/squid.service
    owner: root
    group: root
    mode: 0644
  notify: Reload Avahi
  when: squid_deb_proxy_avahi | bool
